# .github/workflows/update-changelog.yaml
name: "Update Changelog"

on:
  release:
    types: [released]

jobs:
  update-changelog:
    name: Update Changelog
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # updated CHANGELOG back to the repository.
      # https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git fetch --all

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: develop
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md

      - name: Merge changelog
        run: |
          SOURCE=develop
          TARGET=master
          CURRENT_BRANCH=$(git branch --show-current)
          if [ "$CURRENT_BRANCH" != "$TARGET" ]; then
            git checkout develop
          fi
          git pull origin $TARGET
          if git merge --no-ff --allow-unrelated-histories origin/$SOURCE -m "Merge branch '$SOURCE' into $TARGET"; then
            echo "Merge successful for branch $TARGET"
            git push origin $TARGET
          else
            echo "Merge conflict or error occurred for branch $SOURCE. Skipping..."
            git merge --abort
            exit 1
          fi
        
